# Change these first
owner: ConductifyAI # Your GitHub organization or username, where this repository lives
repo: conductify-status # The name of this repository

runner: "[self-hosted]"

assignees:
  - travisnguyen20

sites:
  - name: Conductify Studio
    url: https://studio.conductify.ai
  - name: Conductify API
    url: https://api.conductify.ai/health/liveness
    __dangerous__body_down_if_text_missing: '"status":"ok"'  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /conductify-status
  cname: status.conductify.ai
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Conductify Platform Status Page
  introTitle: Conductify AI Agent Platform
  introMessage: Conductify AI is The No-Code Platform enables to create AI Agents capable of performing complex sequences of activities that previously only humans could do.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
